// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tazohypiucgoiiirxjmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhem9oeXBpdWNnb2lpaXJ4am14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NTc4NzMsImV4cCI6MjA1ODQzMzg3M30.g0cO0J-CaQp19Oo0DRtqFMkXTQjf6q5p3-Z-5jcmgOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);